### ISSUE TITLE
[DslListFilterBuilder] CR/FL characters are not allowed in listFilterBuilderQuery in the "compact syntax" with square bracket

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#51]
The "compact syntax" with braket does not allow carriage return/line feed in listFilterBuilderQuery

This example is not valid:
```
[PRENOM^2, NOM^2, NOM_NAISSANCE^2, NOM_NOM_NAISSANCE_PRENOM, VILLE, CODE_POSTAL, COB_IDNIVOL,
	 NOM_STRUCTURE_RAT, NOM_STRUCTURE_ADH, NOM_STRUCTURE_SAL, NOM_STRUCTURE_ACT, VILLE_STRUCTURE_RAT, VILLE_STRUCTURE_ADH, VILLE_STRUCTURE_SAL
	 ...]:#searchQuery*#
	 +SEARCH_FIELDS:(#+searchQuery*#)
```

The follwing stacktrace is then produced :

```
io.vertigo.lang.WrappedException: Echec de lecture du listFilterPattern [PRENOM^2, NOM^2, NOM_NAISSANCE^2, NOM_NOM_NAISSANCE_PRENOM, VILLE, CODE_POSTAL, COB_IDNIVOL,
	 NOM_STRUCTURE_RAT, NOM_STRUCTURE_ADH, NOM_STRUCTURE_SAL, NOM_STRUCTURE_ACT, VILLE_STRUCTURE_RAT, VILLE_STRUCTURE_ADH, VILLE_STRUCTURE_SAL
	 CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	 DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL, ACTIONS, GROUPE_ACTIONS, ELECTIONS, NOMINATIONS]:#searchQuery*#
	 +SEARCH_FIELDS:(#+searchQuery*#)
Erreur à la ligne 3 colonne 2
	vers :   CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	        ^^^
	1- regle : Terminal ']' is expected
	2- dans regle : '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']'
	3- dans regle : PREM* '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']' PREM*
	4- dans regle : bool? _* PREM* !DEL+ POSTM* | PREM* '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']' PREM* ':' query | rangeQuery | multiQuery | fixedQuery _*

	at io.vertigo.dynamox.search.DslListFilterBuilder.withBuildQuery(DslListFilterBuilder.java:103)
	at fr.croixrouge.dao.benevoles.ContactDAO.createSearchQueryBuilderContactWithFct(ContactDAO.java:76)
	at fr.croixrouge.services.contact.ContactServicesImpl.getContactByCriteria(ContactServicesImpl.java:944)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertigo.util.ClassUtil.invoke(ClassUtil.java:192)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler$MyMethodInvocation.proceed(CGLIBInvocationHandler.java:77)
	at io.vertigo.dynamo.impl.transaction.VTransactionAspect.invoke(VTransactionAspect.java:49)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler$MyMethodInvocation.proceed(CGLIBInvocationHandler.java:75)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler.invoke(CGLIBInvocationHandler.java:52)
	at fr.croixrouge.services.contact.ContactServicesImpl$$EnhancerByCGLIB$$43266d13.getContactByCriteria(<generated>)
	at fr.croixrouge.services.common.CommonServicesImpl.search(CommonServicesImpl.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertigo.util.ClassUtil.invoke(ClassUtil.java:192)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler$MyMethodInvocation.proceed(CGLIBInvocationHandler.java:77)
	at io.vertigo.dynamo.impl.transaction.VTransactionAspect.invoke(VTransactionAspect.java:53)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler$MyMethodInvocation.proceed(CGLIBInvocationHandler.java:75)
	at io.vertigo.core.plugins.component.aop.cglib.CGLIBInvocationHandler.invoke(CGLIBInvocationHandler.java:52)
	at fr.croixrouge.services.common.CommonServicesImpl$$EnhancerByCGLIB$$3ca1d063.search(<generated>)
	at fr.croixrouge.webservices.common.CommonWebServices.search(CommonWebServices.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertigo.util.ClassUtil.invoke(ClassUtil.java:192)
	at io.vertigo.vega.plugins.webservice.handler.RestfulServiceWebServiceHandlerPlugin.handle(RestfulServiceWebServiceHandlerPlugin.java:66)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.ValidatorWebServiceHandlerPlugin.handle(ValidatorWebServiceHandlerPlugin.java:70)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.JsonConverterWebServiceHandlerPlugin.handle(JsonConverterWebServiceHandlerPlugin.java:233)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.SecurityWebServiceHandlerPlugin.handle(SecurityWebServiceHandlerPlugin.java:70)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.RateLimitingWebServiceHandlerPlugin.handle(RateLimitingWebServiceHandlerPlugin.java:110)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.SessionWebServiceHandlerPlugin.handle(SessionWebServiceHandlerPlugin.java:74)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.CorsAllowerWebServiceHandlerPlugin.handle(CorsAllowerWebServiceHandlerPlugin.java:83)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.handler.ExceptionWebServiceHandlerPlugin.handle(ExceptionWebServiceHandlerPlugin.java:73)
	at io.vertigo.vega.plugins.webservice.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.webservice.webserver.sparkjava.SparkJavaRoute.handle(SparkJavaRoute.java:60)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:139)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at io.vertigo.vega.impl.servlet.filter.CacheControlFilter.doMyFilter(CacheControlFilter.java:85)
	at io.vertigo.vega.impl.servlet.filter.AbstractFilter.doFilter(AbstractFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.vertigo.commons.parser.NotFoundException: Erreur à la ligne 3 colonne 2
	vers :   CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	        ^^^
	regle : bool? _* PREM* !DEL+ POSTM* | PREM* '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']' PREM* ':' query | rangeQuery | multiQuery | fixedQuery _*
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:93)
	at io.vertigo.commons.parser.AbstractRule$1.parse(AbstractRule.java:59)
	at io.vertigo.commons.parser.FirstOfRule$1.parse(FirstOfRule.java:89)
	at io.vertigo.commons.parser.ManyRule$1.parse(ManyRule.java:82)
	at io.vertigo.commons.parser.FirstOfRule$1.parse(FirstOfRule.java:89)
	at io.vertigo.commons.parser.AbstractRule$1.parse(AbstractRule.java:59)
	at io.vertigo.commons.parser.ManyRule$1.parse(ManyRule.java:82)
	at io.vertigo.dynamox.search.dsl.rules.DslParserUtil.parseMultiExpression(DslParserUtil.java:49)
	at io.vertigo.dynamox.search.DslListFilterBuilder.withBuildQuery(DslListFilterBuilder.java:100)
	... 70 more
Caused by: io.vertigo.commons.parser.NotFoundException: Erreur à la ligne 3 colonne 2
	vers :   CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	        ^^^
	regle : PREM* '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']' PREM*
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:93)
	at io.vertigo.commons.parser.FirstOfRule$1.parse(FirstOfRule.java:89)
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:89)
	... 78 more
Caused by: io.vertigo.commons.parser.NotFoundException: Erreur à la ligne 3 colonne 2
	vers :   CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	        ^^^
	regle : '[' _* PREM* !DEL+ POSTM* (',' _* PREM* !DEL+ POSTM*)* _* ']'
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:93)
	at io.vertigo.commons.parser.AbstractRule$1.parse(AbstractRule.java:59)
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:89)
	... 80 more
Caused by: io.vertigo.commons.parser.NotFoundException: Erreur à la ligne 3 colonne 2
	vers :   CP_STRUCTURE_RAT, CP_STRUCTURE_ADH, CP_STRUCTURE_SAL, DEPARTEMENT_STRUCTURE_RAT, DEPARTEMENT_STRUCTURE_ADH, DEPARTEMENT_STRUCTURE_SAL
	        ^^^
	regle : Terminal ']' is expected
	at io.vertigo.commons.parser.TermRule.parse(TermRule.java:66)
	at io.vertigo.commons.parser.SequenceRule$1.parse(SequenceRule.java:89)
	... 82 more
```

Version 0.9.0

**Comment by durandx** [comment]
My bad...

**Comment by NPi2Loup** [comment]
Yep, before I start to analyzed this pb :
**Please don't use so many multi fields : use alias**
